2021-04-22T03:51:25.997714700Z -- Attaching packages --------------------------------------- tidyverse 1.3.0 --
2021-04-22T03:51:26.006503700Z v ggplot2 3.3.2     v purrr   0.3.4
2021-04-22T03:51:26.006527300Z v tibble  3.0.3     v dplyr   1.0.2
2021-04-22T03:51:26.006535800Z v tidyr   1.1.2     v stringr 1.4.0
2021-04-22T03:51:26.006543100Z v readr   1.3.1     v forcats 0.5.0
2021-04-22T03:51:26.174127500Z -- Conflicts ------------------------------------------ tidyverse_conflicts() --
2021-04-22T03:51:26.174200300Z x dplyr::filter() masks stats::filter()
2021-04-22T03:51:26.174208500Z x dplyr::lag()    masks stats::lag()
2021-04-22T03:51:26.186871100Z 
2021-04-22T03:51:26.186892500Z Attaching package: 'glue'
2021-04-22T03:51:26.186900200Z 
2021-04-22T03:51:26.188265000Z The following object is masked from 'package:dplyr':
2021-04-22T03:51:26.188334300Z 
2021-04-22T03:51:26.188350200Z     collapse
2021-04-22T03:51:26.188357600Z 
2021-04-22T03:51:28.222905800Z 
2021-04-22T03:51:28.222962400Z Attaching package: 'lubridate'
2021-04-22T03:51:28.222972800Z 
2021-04-22T03:51:28.223429800Z The following objects are masked from 'package:base':
2021-04-22T03:51:28.223451200Z 
2021-04-22T03:51:28.223460200Z     date, intersect, setdiff, union
2021-04-22T03:51:28.223467400Z 
2021-04-22T03:51:28.559813100Z <environment: R_GlobalEnv>
2021-04-22T03:51:28.560248300Z <environment: R_GlobalEnv>
2021-04-22T03:51:58.513356900Z data_pt data size = 7540223 
2021-04-22T03:51:58.515651800Z   memory usage = 3.047 GB 
2021-04-22T03:51:59.048973400Z     
2021-04-22T03:51:59.049056100Z all   
2021-04-22T03:51:59.049066400Z   
2021-04-22T03:52:06.547723300Z   
2021-04-22T03:52:06.795032300Z Error in eval(predvars, data, env) : object 'multimorb' not found
2021-04-22T03:52:06.795106700Z Calls: get_ipw_weights ... eval -> <Anonymous> -> model.frame.default -> eval -> eval
2021-04-22T03:52:06.818353000Z Backtrace:
2021-04-22T03:52:06.818564100Z 1: eval(predvars, data, env)
2021-04-22T03:52:06.818629200Z 2: eval(predvars, data, env)
2021-04-22T03:52:06.818770100Z 3: model.frame.default(formula = ipw_formula, data = data_atrisk, 
2021-04-22T03:52:06.818923400Z 4: stats::model.frame(formula = ipw_formula, data = data_atrisk, 
2021-04-22T03:52:06.819034800Z 5: eval(mf, parent.frame())
2021-04-22T03:52:06.819175500Z 6: eval(mf, parent.frame())
2021-04-22T03:52:06.819284800Z 7: glm(formula = ipw_formula, family = binomial, data = data_atrisk, 
2021-04-22T03:52:06.819374800Z 8: eval(cl, parent.frame())
2021-04-22T03:52:06.819555500Z 9: eval(cl, parent.frame())
2021-04-22T03:52:06.819672100Z 10: parglm(formula = ipw_formula, data = data_atrisk, family = binomial, 
2021-04-22T03:52:06.819798400Z 11: get_ipw_weights(data_pt_sub, "vaxany1", "vaxany1_status", "vaxany1_atrisk", 
2021-04-22T03:52:10.794867300Z vaxany1  

state: failed
commit: f1fd270c0518dd34d87dddd6887c60798415b647
docker_image_id: sha256:c2fc5042bf86134947d83ad8e70bd926e2c1f91a263c6bfe87438ad783bec981
exit_code: 1
job_id: at4sjofyqgjj7pmo
run_by_user: wjchulme
created_at: 2021-04-21T19:25:38Z
started_at: 2021-04-22T03:51:23Z
completed_at: 2021-04-22T03:52:15Z

Job exited with an error code

outputs:
  (no outputs)