2021-04-22T03:52:03.080964000Z -- Attaching packages --------------------------------------- tidyverse 1.3.0 --
2021-04-22T03:52:03.089103200Z v ggplot2 3.3.2     v purrr   0.3.4
2021-04-22T03:52:03.089128900Z v tibble  3.0.3     v dplyr   1.0.2
2021-04-22T03:52:03.089138100Z v tidyr   1.1.2     v stringr 1.4.0
2021-04-22T03:52:03.089145300Z v readr   1.3.1     v forcats 0.5.0
2021-04-22T03:52:03.250334400Z -- Conflicts ------------------------------------------ tidyverse_conflicts() --
2021-04-22T03:52:03.250403700Z x dplyr::filter() masks stats::filter()
2021-04-22T03:52:03.250412700Z x dplyr::lag()    masks stats::lag()
2021-04-22T03:52:03.262730500Z 
2021-04-22T03:52:03.262752800Z Attaching package: 'glue'
2021-04-22T03:52:03.262761000Z 
2021-04-22T03:52:03.264074700Z The following object is masked from 'package:dplyr':
2021-04-22T03:52:03.264090900Z 
2021-04-22T03:52:03.264101100Z     collapse
2021-04-22T03:52:03.264108300Z 
2021-04-22T03:52:05.324268600Z 
2021-04-22T03:52:05.324338800Z Attaching package: 'lubridate'
2021-04-22T03:52:05.324347700Z 
2021-04-22T03:52:05.324775400Z The following objects are masked from 'package:base':
2021-04-22T03:52:05.324797900Z 
2021-04-22T03:52:05.324807400Z     date, intersect, setdiff, union
2021-04-22T03:52:05.324814900Z 
2021-04-22T03:52:05.657492600Z <environment: R_GlobalEnv>
2021-04-22T03:52:05.657950300Z <environment: R_GlobalEnv>
2021-04-22T03:52:35.389163500Z data_pt data size = 7606081 
2021-04-22T03:52:35.391688300Z   memory usage = 3.073 GB 
2021-04-22T03:52:35.922057600Z     
2021-04-22T03:52:35.922134800Z all   
2021-04-22T03:52:35.922144100Z   
2021-04-22T03:52:43.388919600Z   
2021-04-22T03:52:43.633578300Z Error in eval(predvars, data, env) : object 'multimorb' not found
2021-04-22T03:52:43.633667400Z Calls: get_ipw_weights ... eval -> <Anonymous> -> model.frame.default -> eval -> eval
2021-04-22T03:52:43.655882000Z Backtrace:
2021-04-22T03:52:43.655975700Z 1: eval(predvars, data, env)
2021-04-22T03:52:43.656107600Z 2: eval(predvars, data, env)
2021-04-22T03:52:43.656230700Z 3: model.frame.default(formula = ipw_formula, data = data_atrisk, 
2021-04-22T03:52:43.656430600Z 4: stats::model.frame(formula = ipw_formula, data = data_atrisk, 
2021-04-22T03:52:43.656547800Z 5: eval(mf, parent.frame())
2021-04-22T03:52:43.656668300Z 6: eval(mf, parent.frame())
2021-04-22T03:52:43.656791800Z 7: glm(formula = ipw_formula, family = binomial, data = data_atrisk, 
2021-04-22T03:52:43.656916200Z 8: eval(cl, parent.frame())
2021-04-22T03:52:43.657038600Z 9: eval(cl, parent.frame())
2021-04-22T03:52:43.657166200Z 10: parglm(formula = ipw_formula, data = data_atrisk, family = binomial, 
2021-04-22T03:52:43.657344400Z 11: get_ipw_weights(data_pt_sub, "vaxany1", "vaxany1_status", "vaxany1_atrisk", 
2021-04-22T03:52:48.035044300Z vaxany1  

state: failed
commit: f1fd270c0518dd34d87dddd6887c60798415b647
docker_image_id: sha256:c2fc5042bf86134947d83ad8e70bd926e2c1f91a263c6bfe87438ad783bec981
exit_code: 1
job_id: iotoyi5pbeloypvr
run_by_user: wjchulme
created_at: 2021-04-21T19:25:38Z
started_at: 2021-04-22T03:52:00Z
completed_at: 2021-04-22T03:52:50Z

Job exited with an error code

outputs:
  (no outputs)